'use strict';
window.renderSportCenter=function(payload){
const decodeText=v=>String(v??'').replace(/&(amp|lt|gt|quot|#39|#96);/g,(_,k)=>({amp:'&',lt:'<',gt:'>',quot:'\"','#39':"'",'#96':'`'}[k]));
const D=payload;
const cuponesPorCodigo=[...D.cupones].sort((a,b)=>Number(b.codigo.replace(/\D/g,''))-Number(a.codigo.replace(/\D/g,'')));
const money=c=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',minimumFractionDigits:c%100?2:0,maximumFractionDigits:2}).format(c/100);
const foreignMoney=(c,currency)=>`${currency} $${new Intl.NumberFormat('es-CL',{minimumFractionDigits:c%100?2:0,maximumFractionDigits:2}).format(c/100)}`;
const num=n=>n==null?'—':new Intl.NumberFormat('es-CL',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n??0);
const esc=v=>String(v??'');
const statusClass=s=>/PERD/i.test(s)?'lost':/GANAD/i.test(s)?'win':'playing';
const legIcon=s=>/ACERT/i.test(s)?'🟢':/PERD/i.test(s)?'🔴':'🟡';
const sportIcon=s=>({NFL:'🏈',NCAA:'🏈',MLB:'⚾',NHL:'🏒',NBA:'🏀',WNBA:'🏀',FÚTBOL:'⚽',FUTBOL:'⚽',SOCCER:'⚽',TENIS:'🎾',TENNIS:'🎾',HÍPICA:'🏇',HIPICA:'🏇'}[String(s||'').toUpperCase()]||'🏅');
const playerIdentity=(position,number,team)=>position&&team?`${esc(position)}${number==null?'':` · #${esc(number)}`} · ${esc(team)}`:'';
const propIdentity=p=>playerIdentity(p.posicion_jugador,p.dorsal_jugador,p.equipo_jugador);
const cutClass=s=>/SUPERADA|CUMPLIENDO/.test(s)?'cut-good':/PERDIDA|FALLANDO/.test(s)?'cut-bad':'cut-pending';
const cutLabel=c=>c?`<span class="leg-cut ${cutClass(c.estado_provisional)}"><b>${esc(c.corte.replaceAll('_',' '))} · ${esc(c.estado_provisional)}</b>${esc(c.detalle)}</span>`:'';
document.querySelector('#data-cut').textContent=decodeText(`Corte: ${D.meta.corte_label}`);
document.querySelector('#generated-at').textContent=decodeText(`Generado: ${D.meta.generado_label}`);

const saldoBetanoValido=D.resumen.saldo_betano_disponible_centavos>=0;
const saldoBetanoConfirmado=D.resumen.saldo_betano_validacion==='CONFIRMADO_POR_ORLANDO'&&D.resumen.saldo_betano_confirmado_usuario_centavos===D.resumen.saldo_betano_disponible_centavos;
const metrics=[
 [saldoBetanoConfirmado?'Saldo disponible Betano':D.resumen.saldo_betano_estado?'Saldo Betano calculado':'Saldo disponible Betano',saldoBetanoValido?money(D.resumen.saldo_betano_disponible_centavos):'Pendiente de confirmar',saldoBetanoValido?(saldoBetanoConfirmado?'Confirmado por Orlando':D.resumen.saldo_betano_estado?'Pendiente de confirmación en Betano':'saldo base + depósitos − retiros − apuestas + cobros'):'los cupones nuevos prueban fondos posteriores no registrados'],
 ['Apuesta activa',money(D.resumen.apuesta_activa_centavos),`${D.resumen.cupones_activos} cupones activos${D.cupones.some(c=>c.apuesta_gratis_centavos)?` · ${money(D.cupones.reduce((n,c)=>n+(c.apuesta_gratis_centavos||0),0))} en apuestas gratis aparte`:""}`],
 ['Cobro potencial total',money(D.resumen.cobro_potencial_centavos),'si aciertan los cupones vigentes'],
 ['Ganancia neta potencial',money(D.resumen.ganancia_neta_centavos),'sobre el capital activo']];
document.querySelector('#summary-cards').innerHTML=metrics.map(([a,b,c])=>`<article class="metric"><div class="label">${a}</div><div class="value">${b}</div><div class="sub">${c}</div></article>`).join('');
document.querySelector('#resumen .notice').innerHTML=saldoBetanoValido
 ?`<strong>Cálculo Betano:</strong> ${money(D.resumen.saldo_betano_base_centavos)} de saldo base + ${money(D.resumen.saldo_betano_depositos_centavos)} depositados − ${money(D.resumen.saldo_betano_retiros_centavos||0)} retirados − ${money(D.resumen.saldo_betano_debitos_centavos)} apostados + ${money(D.resumen.saldo_betano_abonos_centavos)} de cupones ganados confirmados ${D.resumen.saldo_betano_ajustes_centavos>=0?'+':'−'} ${money(Math.abs(D.resumen.saldo_betano_ajustes_centavos||0))} de ajustes confirmados = <strong>${money(D.resumen.saldo_betano_disponible_centavos)} disponibles</strong>.`
 :`<strong>Saldo Betano pendiente:</strong> los cupones nuevos suman apuestas posteriores al último saldo confirmado. No se muestra un saldo negativo ficticio; falta registrar el depósito o saldo más reciente.`;

if(saldoBetanoConfirmado) document.querySelector('#resumen .notice').textContent=D.resumen.saldo_betano_estado;
else if(D.resumen.saldo_betano_estado) document.querySelector('#resumen .notice').textContent=D.resumen.saldo_betano_estado+' · Los totales activos incluyen cupones pendientes de conciliación.';

const H=D.hipica;
document.querySelector('#hipica-count').textContent=decodeText(`${H.carreras.length} carreras · ${H.modelo==='EFICIENCIA_50_50'?'Modelo 50/50':`${H.medios} medios`}`);
document.querySelector('#hipica-method').innerHTML=`<strong>Corte ${esc(H.fecha)}:</strong> ${esc(H.metodologia)} El primero de cada tarjeta es la selección principal sugerida para la polla.`;
const hipicaStrong=H.sugerencias.filter(s=>s.nivel==='FUERTE');
const hipicaBackup=H.sugerencias.filter(s=>s.nivel==='RESPALDO');
const hipicaPick=s=>`<article class="hipica-pick ${s.nivel==='FUERTE'?'hipica-pick-strong':''} ${s.estado_resultado==='PERDIDA'?'hipica-pick-lost':s.estado_resultado==='ACERTADA'?'hipica-pick-win':''}"><span>C${s.carrera}</span><div><strong>#${s.seleccion} · ${esc(s.caballo)}</strong><small>${esc(s.motivo)}</small></div><em>${s.estado_resultado==='PENDIENTE'?(s.nivel==='FUERTE'?'COINCIDENCIA FUERTE':'RESPALDO'):esc(s.estado_resultado)}</em></article>`;
const pollaCut=H.polla_corte||{};
document.querySelector('#hipica-suggestions').innerHTML=`<div class="hipica-suggestion-head"><div><span>APUESTAS SUGERIDAS · ${esc(H.fecha)}</span><strong>${pollaCut.carreras_revisadas?`Polla La Sexta: ${pollaCut.aciertos}/${pollaCut.carreras_revisadas} hasta C${pollaCut.hasta_carrera}`:`${hipicaStrong.length} coincidencias fuertes`}</strong></div><p>${esc(H.sugerencias_metodo)}</p></div><div class="hipica-pick-block"><h3>Prioridad</h3><div class="hipica-pick-list">${hipicaStrong.map(hipicaPick).join('')}</div></div><div class="hipica-pick-block"><h3>Alternativas de respaldo</h3><div class="hipica-pick-list">${hipicaBackup.map(hipicaPick).join('')}</div></div>`;
document.querySelector('#hipica-ranking').innerHTML=H.carreras.map(r=>`<article class="hipica-card"><div class="hipica-head"><div><span>CARRERA ${r.carrera}</span><strong>${esc(r.hora)} · ${esc(r.descripcion)}</strong></div><span>🏇</span></div>${r.resultado?`<div class="hipica-result"><span>RESULTADO OFICIAL</span><strong>#${r.resultado.ganador_numero} · ${esc(r.resultado.ganador)}</strong></div>`:''}<ol>${r.ranking.map(h=>`<li class="${h.puesto===1?'hipica-leader':''} ${r.resultado&&h.numero===r.resultado.ganador_numero?'hipica-winner':''}"><span class="hipica-place">${h.puesto}</span><div class="hipica-horse"><strong>#${h.numero} · ${esc(h.caballo)}</strong><small>${h.indice!=null?`Índice ${num(h.indice)}${H.modelo==='EFICIENCIA_50_50'?' · eficiencia 50/50':` · ${h.puntos_prensa} pts de consenso`}`:`${h.puntos_prensa} pts · ${h.primeros_prensa} primeras · ${h.menciones_prensa} menciones`}</small><small>Jinete ${h.jinete?`${esc(h.jinete)} · `:''}${num(h.jinete_pct)}% | Preparador ${h.preparador?`${esc(h.preparador)} · `:''}${num(h.preparador_pct)}%</small></div>${r.resultado&&h.numero===r.resultado.ganador_numero?'<em>GANADOR</em>':h.puesto===1?'<em>SELECCIÓN</em>':''}</li>`).join('')}</ol>${(r.pendientes||[]).length?`<p class="muted">Pendiente de jinete: ${r.pendientes.map(p=>`#${p.caballo_numero} ${esc(p.caballo)}`).join(', ')}. Clasificación entre los ejemplares evaluables.</p>`:''}</article>`).join('');
if(H.modelo==='EFICIENCIA_50_50' && !H.sugerencias.length) document.querySelector('#hipica-suggestions').hidden=true;
const hipicaCoupons=H.cupones||[];
const hipicaStake=hipicaCoupons.reduce((total,c)=>total+c.apuesta_centavos,0);
const hipicaKnownReturns=hipicaCoupons.every(c=>c.cobro_potencial_centavos!=null);
const hipicaKnownNet=hipicaCoupons.every(c=>c.ganancia_neta_potencial_centavos!=null);
document.querySelector('#hipica-coupon-count').textContent=decodeText(`${hipicaCoupons.length} cupones activos`);
document.querySelector('#hipica-coupon-summary').innerHTML=[
 ['Apuesta activa',money(hipicaStake),`${hipicaCoupons.length} apuestas a ganador`],
 ['Cobro potencial total',hipicaKnownReturns?money(hipicaCoupons.reduce((t,c)=>t+c.cobro_potencial_centavos,0)):'Pendiente de dividendo','se completa al revisar el pago oficial'],
 ['Ganancia neta potencial',hipicaKnownNet?money(hipicaCoupons.reduce((t,c)=>t+c.ganancia_neta_potencial_centavos,0)):'Pendiente de dividendo','cobro menos apuesta']
].map(([a,b,c])=>`<article class="metric hipica-coupon-metric"><div class="label">${a}</div><div class="value">${b}</div><div class="sub">${c}</div></article>`).join('');
document.querySelector('#hipica-coupon-list').innerHTML=hipicaCoupons.map(c=>`<article class="coupon hipica-coupon"><div class="coupon-head"><div><div class="code">${esc(c.codigo)}</div><div class="event">Carrera ${c.carrera} · ${esc(c.hora_carrera)} · Hipódromo Chile</div></div><span class="status playing">${esc(c.estado)}</span></div><div class="money-row"><div class="money"><span>Apuesta</span><strong>${c.apuesta_gratis_centavos?`${money(c.apuesta_gratis_centavos)} gratis`:money(c.apuesta_centavos)}</strong></div><div class="money"><span>Cobro potencial</span><strong>${c.cobro_potencial_centavos==null?'Pendiente':money(c.cobro_potencial_centavos)}</strong></div><div class="money"><span>Ganancia neta potencial</span><strong>${c.ganancia_neta_potencial_centavos==null?'Pendiente':money(c.ganancia_neta_potencial_centavos)}</strong></div></div><div class="hipica-coupon-pick"><span>#${c.caballo_numero}</span><div><strong>${esc(c.caballo)}</strong><small>${esc(c.mercado)} · ${esc(c.descripcion)}</small></div><em>APUESTA ${esc(c.hora_apuesta)}</em></div><div class="settlement hipica-coupon-meta"><span>Fecha: <strong>${esc(c.fecha)}</strong></span><span>Serie: <strong>${esc(c.serial)}</strong></span></div></article>`).join('');

const DS=D.estadisticas_doctor,totalDoctor=DS.total;
const signedMoney=c=>c>0?`+${money(c)}`:c<0?`-${money(-c)}`:money(0);
const doctorRecord=s=>`${s.cupones_ganados} ganados · ${s.cupones_perdidos} perdidos · ${s.cupones_pendientes} pendientes`;
const doctorSelectionRecord=s=>`${s.selecciones_acertadas} aciertos · ${s.selecciones_perdidas} pérdidas · ${s.selecciones_pendientes} pendientes`;
const doctorPeriod=s=>`<article class="doctor-period"><div><strong>${esc(s.label)}</strong><small>${doctorRecord(s)} · ${doctorSelectionRecord(s)}</small></div><div class="doctor-period-money"><span>Apostado <b>${money(s.apostado_centavos)}</b></span><span>Cobrado <b>${money(s.cobrado_centavos)}</b></span><span>Neto total <b class="${s.resultado_total_centavos>=0?'positive':'negative'}">${signedMoney(s.resultado_total_centavos)}</b></span></div></article>`;
document.querySelector('#doctor-count').textContent=decodeText(`${totalDoctor.cupones} cupones identificados`);
document.querySelector('#doctor-investment').innerHTML=`<strong>Inversión inicial incluida:</strong> USD ${new Intl.NumberFormat('es-CL').format(DS.inversion_inicial_usd_centavos/100)} × ${num(DS.tipo_cambio_clp_usd)} CLP/USD = <strong>${money(totalDoctor.inversion_inicial_centavos)}</strong>. Esta inversión se descuenta una sola vez del resultado total.`;
document.querySelector('#doctor-summary').innerHTML=[
 ['Cupones',doctorRecord(totalDoctor),`${totalDoctor.cupones} ratificados por Orlando`],
 ['Selecciones',doctorSelectionRecord(totalDoctor),`${totalDoctor.selecciones} selecciones contabilizadas`],
 ['Dinero apostado',money(totalDoctor.apostado_centavos),totalDoctor.apuesta_gratis_centavos?`dinero propio · ${money(totalDoctor.apuesta_gratis_centavos)} en apuestas gratis aparte`:'solo cupones del Doctor'],
 ['Dinero cobrado',money(totalDoctor.cobrado_centavos),'cobros liquidados'],
 ['Neto de apuestas',signedMoney(totalDoctor.resultado_apuestas_centavos),'cobrado menos apostado'],
 ['Neto total',signedMoney(totalDoctor.resultado_total_centavos),'incluye la inversión inicial']
].map(([a,b,c])=>`<article class="metric doctor-metric"><div class="label">${a}</div><div class="value">${b}</div><div class="sub">${c}</div></article>`).join('');
document.querySelector('#doctor-coupons').innerHTML=DS.cupones_detalle.map(c=>`<article class="doctor-coupon-state"><div class="doctor-coupon-state-head"><div><strong>${esc(c.codigo)}</strong><small>${esc(c.evento)}</small></div><span class="status ${statusClass(c.estado)}">${c.estado==='ACTIVO'?'PENDIENTE':esc(c.estado)}</span></div><ul>${c.selecciones.map(s=>`<li><span>${legIcon(s.estado)}</span><span>${esc(s.seleccion)}<small>${esc(s.estado)}</small></span></li>`).join('')}</ul></article>`).join('');
document.querySelector('#doctor-daily').innerHTML=DS.diario.map(doctorPeriod).join('');
document.querySelector('#doctor-weekly').innerHTML=DS.semanal.map(doctorPeriod).join('');

const W=D.revision_semanal_fantasy;
document.querySelector('#weekly-review-note').innerHTML=`<strong>Corte ${esc(W.corte)}:</strong> revisión de standings, rosters, rivales, waivers/agentes libres, lesiones y lineups. ${esc(W.fuente)} Ningún bid, alta, baja, drop, trade o cambio de lineup fue ejecutado por el asistente.`;
const reviewRow=(label,value)=>`<div class="weekly-review-row"><strong>${label}</strong><p>${esc(value)}</p></div>`;
document.querySelector('#weekly-review').innerHTML=W.ligas.map(l=>`<article class="weekly-review-card"><div class="weekly-review-head"><div><div class="league-name">${esc(l.liga_codigo)}</div><div class="league-format">Semana ${W.semana}</div></div><span class="status ${l.accion_estado==='SIN ACCIÓN'?'active':'playing'}">${esc(l.accion_estado)}</span></div>${reviewRow('STANDINGS',l.standings_resumen)}${reviewRow('ROSTER',l.roster_resumen)}${reviewRow('RIVAL',l.rival_resumen)}${reviewRow('WAIVERS / LIBRES',l.waivers_resumen)}${reviewRow('LESIONES',l.lesiones_resumen)}${reviewRow('LINEUP',l.lineup_resumen)}<div class="weekly-action"><strong>ACCIÓN PROPUESTA</strong><p>${esc(l.accion_propuesta)}</p></div></article>`).join('');

const F=D.finanzas;
document.querySelector('#finance-alert').innerHTML=`<strong>${esc(F.estado)}:</strong> ${esc(F.advertencia)}`;
document.querySelector('#finance-summary').innerHTML=[
 ['Total cuentas y productos',money(F.resumen.saldo_productos_centavos),'saldos fotografiados'],
 ['Variación preliminar',money(F.resumen.diferencia_productos_centavos),'aún no es gasto ni ingreso'],
 ['Reservas Mercado Pago',money(F.resumen.reservas_total_centavos),`${money(F.resumen.reservas_propias_centavos)} propias`],
 ['Pendientes',String(F.resumen.pendientes_movimientos),'bloques requieren movimientos']
].map(([a,b,c])=>`<article class="metric"><div class="label">${a}</div><div class="value">${b}</div><div class="sub">${c}</div></article>`).join('');
document.querySelector('#finance-accounts').innerHTML=F.cuentas.map(c=>`<article class="finance-account"><div><strong>${esc(c.producto_nombre)}</strong><small>Anterior ${money(c.saldo_anterior_centavos)} · variación ${money(c.diferencia_centavos)}</small>${c.evidencia_visible?`<small>${esc(c.evidencia_visible)}</small>`:''}</div><div><span>${money(c.saldo_centavos)}</span><em>${esc(c.conciliacion_estado.replaceAll('_',' '))}</em></div></article>`).join('')+F.reservas.map(r=>`<article class="finance-account"><div><strong>Reserva · ${esc(r.reserva_nombre)}</strong><small>Anterior ${money(r.saldo_anterior_centavos)} · variación ${money(r.diferencia_centavos)}</small></div><div><span>${money(r.saldo_centavos)}</span><em>${r.requiere_movimientos?'PENDIENTE MOVIMIENTOS':'CONCILIADO'}</em></div></article>`).join('');
document.querySelector('#finance-drive').removeAttribute('href'); document.querySelector('#finance-drive').textContent='Enlace externo omitido en el visor local';
document.querySelector('#finance-movements').innerHTML=F.pendientes.map(nombre=>`<article class="finance-movement"><div class="movement-date">PENDIENTE</div><div class="movement-copy"><strong>${esc(nombre)}</strong><small>Subir pantallazo de movimientos para conciliar la variación</small><span>Variación superior a $500</span></div></article>`).join('');

document.querySelector('#coupon-count').textContent=decodeText(`${cuponesPorCodigo.length} cupones`);
const C=D.ultimo_cierre;
document.querySelector('#last-settlement').innerHTML=`<article class="last-settlement"><div><span>Último cierre</span><strong>${esc(C.evento)}</strong><small>${C.ganados} ganados · ${C.perdidos} perdidos</small></div><div class="settlement-total ${C.resultado_neto_centavos>=0?'positive':'negative'}"><span>Ganado / perdido</span><strong>${C.resultado_neto_centavos>=0?'+':''}${money(C.resultado_neto_centavos)}</strong></div><div class="settlement-coupons">${C.cupones.map(c=>`<span class="${statusClass(c.estado)}"><b>${esc(c.codigo)}</b> ${c.resultado_neto_centavos>=0?'+':''}${money(c.resultado_neto_centavos)}</span>`).join('')}</div></article>`;
document.querySelector('#coupon-list').innerHTML=cuponesPorCodigo.map(c=>`<article class="coupon ${c.doctor?'doctor-coupon':''}"><div class="coupon-head"><div><div class="code">${c.codigo}${c.doctor?` <span class="doctor-badge">🩺 ${esc(c.doctor.fuente_doctor)}${c.doctor.tipo_recomendacion==='ALTERNATIVA_ADAPTADA'?' · ALTERNATIVA ADAPTADA':''}</span>`:''}</div><div class="event">${c.evento_principal}</div></div><span class="status ${statusClass(c.estado)}">${c.estado}</span></div><div class="money-row"><div class="money"><span>Apuesta</span><strong>${c.apuesta_gratis_centavos?`${money(c.apuesta_gratis_centavos)} gratis`:money(c.apuesta_centavos)}</strong></div><div class="money"><span>Cobro potencial</span><strong>${money(c.cobro_potencial_centavos)}</strong></div><div class="money"><span>Ganancia neta potencial</span><strong>${money(c.ganancia_neta_potencial_centavos)}</strong></div></div>${c.estado==='ACTIVO'?`<div class="settlement">${c.bono_potencial_centavos?`<span>Bono incluido: <strong>${money(c.bono_potencial_centavos)}</strong></span>`:''}<span>Cash out visible: <strong>${money(c.cashout_centavos||0)}</strong></span></div>`:`<div class="settlement"><span>Cobro liquidado: <strong>${money(c.cobro_liquidado_centavos||0)}</strong></span><span>Resultado neto: <strong>${money(c.resultado_neto_centavos)}</strong></span></div>`}${c.piernas.length?`<ul class="legs">${c.piernas.map(p=>`<li class="leg"><span>${legIcon(p.estado)}</span><span>${p.seleccion}<small>${propIdentity(p)?`${propIdentity(p)} · `:''}${p.mercado} · ${p.estado}</small>${cutLabel(p.corte)}</span></li>`).join('')}</ul>`:''}</article>`).join('');

document.querySelector('#future-count').textContent=decodeText(`${D.resumen_largo_plazo.cupones} apuestas vigentes`);
document.querySelector('#future-summary').innerHTML=[
 ['Inversión total',D.resumen_largo_plazo.inversion_centavos],
 ['Retorno potencial',D.resumen_largo_plazo.retorno_potencial_centavos],
 ['Ganancia neta potencial',D.resumen_largo_plazo.ganancia_neta_potencial_centavos]
].map(([label,value])=>`<article class="future-metric"><span>${label}</span><strong>${money(value)}</strong></article>`).join('');
document.querySelector('#future-summary').insertAdjacentHTML('afterend',D.resumen_largo_plazo.retornos_pendientes?`<p class="notice"><strong>Survivor incluido en la inversión:</strong> su premio bruto se muestra convertido a CLP de forma referencial; el retorno neto y la ganancia total aún no lo incluyen porque falta la comisión real de PayPal.</p>`:'');
document.querySelector('#future-list').innerHTML=D.apuestas_largo_plazo.map(c=>{
 const standardMoney=`<div class="money-row"><div class="money"><span>Inversión</span><strong>${money(c.inversion_centavos)}</strong></div><div class="money"><span>Retorno potencial</span><strong>${money(c.retorno_potencial_centavos)}</strong></div><div class="money"><span>Ganancia neta potencial</span><strong>${money(c.ganancia_neta_potencial_centavos)}</strong></div></div>`;
 const fxBackup=c.premio_clp_estimado_centavos?`${foreignMoney(c.premio_bruto_centavos,c.premio_moneda)} · ${num(c.tipo_cambio_clp_por_moneda)} CLP/${esc(c.premio_moneda)} · ${esc(c.tipo_cambio_fecha)}`:'';
 const pendingMoney=`<div class="money-row"><div class="money"><span>Inversión total</span><strong>${money(c.inversion_centavos)}</strong></div><div class="money"><span>Premio bruto estimado</span><strong>${c.premio_clp_estimado_centavos?money(c.premio_clp_estimado_centavos):foreignMoney(c.premio_bruto_centavos,c.premio_moneda)}</strong>${fxBackup?`<small>${fxBackup}</small>`:''}</div><div class="money"><span>Premio neto</span><strong>Pendiente comisión</strong></div></div><div class="notice"><strong>Conversión referencial:</strong> ${esc(c.detalle_financiero)}${c.tipo_cambio_fuente?` Fuente: ${esc(c.tipo_cambio_fuente)}.`:''}</div>`;
 const payments=c.pagos.length?`<ul class="legs">${c.pagos.map(p=>`<li class="leg future-leg"><span>💳</span><span>${esc(p.referencia)}<small>${esc(p.descripcion)}</small></span><strong class="pick-progress">${money(p.monto_clp_centavos)}</strong></li>`).join('')}</ul>`:'';
 return `<article class="coupon future-coupon"><div class="coupon-head"><div><div class="code">${c.codigo}</div><div class="event">${c.titulo}</div></div><span class="status playing">${c.estado}</span></div>${c.retorno_calculable?standardMoney:pendingMoney}<div class="future-meta"><span>${c.tipo}</span>${c.retorno_calculable?`<span>Cuota ${num(c.cuota)}</span>`:''}<span>Hito ${c.fecha_hito}</span></div>${payments}<ul class="legs">${c.piernas.map(p=>`<li class="leg future-leg"><span>🟡</span><span>${p.seleccion}<small>${propIdentity(p)?`${propIdentity(p)} · `:''}${c.retorno_calculable?`Cuota ${num(p.cuota)}`:'Selección confirmada'}</small></span><strong class="pick-progress">${p.avance||'Pendiente de actualización'}</strong></li>`).join('')}</ul></article>`;
}).join('');

document.querySelector('#fantasy-list').innerHTML=D.fantasy.map(l=>`<article class="league"><div><div class="league-name">${l.codigo}</div><div class="league-format">${l.formato}</div><span class="status ${statusClass(l.estado_semana)}">${l.estado_semana}</span></div><div class="score"><div class="score-block"><span>🟢 TÚ</span><strong>${num(l.marcador_propio)}</strong></div><div class="versus">${l.marcador_rival==null?'—':'VS'}</div><div class="score-block"><span>🔴 ${l.rival||'SIN RIVAL H2H'}</span><strong>${l.marcador_rival==null?'—':num(l.marcador_rival)}</strong></div></div><div class="league-copy"><p><strong>${l.condicion_resultado}</strong></p><p class="muted">${l.nota_clasificacion}</p><p class="muted">${l.posibilidad_aumentar}</p><p class="live-count"><strong>JUGANDO AHORA:</strong> 🟢 ${l.jugando_ahora_propio}${l.marcador_rival==null?' · sin rival H2H':` vs 🔴 ${l.jugando_ahora_rival}`} · último partido</p></div></article>`).join('');

const rivalByLeague=Object.fromEntries(D.rivales_probables.map(l=>[l.codigo,l]));
const projected=p=>p.puntos_proyectados==null?'s/p':`${num(p.puntos_proyectados)} pts`;
const scoreNow=p=>p.puntos_actuales==null?'pendiente':`${num(p.puntos_actuales)} pts`;
const participation=p=>p.jugando_ahora?'EN JUEGO · ÚLTIMO PARTIDO':p.estado_participacion==='NO_JUGO'?'no jugó':p.partido_finalizado?'final':p.corte_revisado?esc(p.corte_revisado.replaceAll('_',' ').toLowerCase()):p.estado==='TITULAR'?'por jugar':p.estado.toLowerCase();
const starterCard=p=>`<div class="starter ${/CONDICIONAL|CAMBIO PROBABLE/.test(p.estado)?'conditional':''}"><span class="starter-slot">${p.slot}</span><span><strong>${p.nombre} <b class="player-projection">${scoreNow(p)} (${projected(p)})</b></strong><small>${p.posicion}${p.dorsal==null?' #—':` #${p.dorsal}`} · ${p.equipo_nfl} · ${p.rival_semana}</small></span><em>${participation(p)}</em></div>`;
const reserveCard=p=>`<div class="reserve ${p.estado==='IR'||p.estado==='BAJA PROBABLE'?'reserve-alert':''}"><span><strong>${p.nombre} <b class="player-projection">${scoreNow(p)} (${projected(p)})</b></strong><small>${p.posicion}${p.dorsal==null?' #—':` #${p.dorsal}`} · ${p.equipo_nfl} · ${p.rival_semana}</small></span><em>${participation(p)}</em></div>`;
document.querySelector('#lineup-comparisons').innerHTML=D.alineaciones_propuestas.map(own=>{const rival=rivalByLeague[own.codigo];const side=(title,subtitle,status,actual,projection,starters,bench,criterion,alert)=>`<section class="matchup-team"><div class="team-head"><div><h3>${title}</h3><span>${subtitle}</span></div><div class="team-summary"><span>Actual · proyección</span><strong>${actual} · ${projection}</strong></div></div><span class="status playing team-status">${status}</span><h4>Titulares</h4>${starters.length?`<div class="starter-list">${starters.map(starterCard).join('')}</div>`:'<p class="empty-roster">Sin jugadores · no existe rival H2H</p>'}<h4>Banca e IR</h4>${bench.length?`<div class="reserve-list">${bench.map(reserveCard).join('')}</div>`:'<p class="empty-roster">Sin banca rival</p>'}<div class="lineup-reason"><p><strong>Criterio:</strong> ${criterion}</p><p><strong>Alerta:</strong> ${alert}</p></div></section>`;const ownActual=num(own.puntos_actuales_total),ownProjection=own.proyeccion_total==null?'s/p':num(own.proyeccion_total);const rivalActual=rival.titulares.length?num(rival.puntos_actuales_total):'—',rivalProjection=rival.titulares.length?(rival.proyeccion_total==null?'s/p':num(rival.proyeccion_total)):'—';return `<article class="matchup-card"><div class="matchup-title"><div><div class="league-name">${own.codigo}</div><div class="league-format">Semana ${own.semana} · puntos actuales (proyección inicial)</div></div><div class="projection-score"><span>🟢 TÚ <strong>${ownActual} (${ownProjection})</strong></span><i>VS</i><span>🔴 ${rival.rival||'SIN RIVAL H2H'} <strong>${rivalActual} (${rivalProjection})</strong></span></div></div><div class="matchup-columns">${side('🟢 TÚ','Team Orlando',own.estado,ownActual,ownProjection,own.titulares,own.banca,own.criterio,own.alerta)}${side(`🔴 ${rival.rival||'SIN RIVAL H2H'}`,rival.rival?'Rival directo':'Formato Guillotine',rival.estado,rivalActual,rivalProjection,rival.titulares,rival.banca,rival.criterio,rival.alerta)}</div></article>`}).join('');

document.querySelector('#waiver-proposals').innerHTML=D.waivers_propuestos.map(l=>`<article class="waiver-card"><div class="lineup-head"><div><div class="league-name">${l.codigo}</div><div class="league-format">${esc(l.estado||(l.movimientos.length?'Pool verificado':'Sin compra recomendada'))}</div></div><span class="status ${l.movimientos.length?'playing':'active'}">${esc(l.estado||(l.movimientos.length?`${l.movimientos.length} OBJETIVOS`:'MANTENER'))}</span></div>${l.movimientos.length?`<div class="waiver-list">${l.movimientos.map(m=>`<div class="waiver-move"><div class="waiver-rank">${m.prioridad}</div><div><strong>${m.jugador}</strong><small>${playerIdentity(m.posicion,m.dorsal,m.equipo_nfl)} · ${m.tipo}</small><p>${m.motivo}</p><div class="waiver-action"><span>Bid <b>$${m.bid_faab}</b></span><span>Cortar <b>${m.cortar}</b></span></div></div><em>${m.recomendacion}</em></div>`).join('')}</div>`:`<p class="no-move">${esc(l.nota||'Sin propuesta nueva registrada.')}</p>`}</article>`).join('');

document.querySelector('#standings-list').innerHTML=D.posiciones.map(t=>{const weeklyGuillotine=t.modo_tabla==='SEMANA_4_GUILLOTINE';if(weeklyGuillotine)return `<article class="standings"><h3>${esc(t.codigo)} · SEMANA ${t.semana||4} · ${t.provisional?'PROVISIONAL':'CIERRE OFICIAL'}</h3><div class="table-scroll"><table><thead><tr><th># S4</th><th>Equipo</th><th>Puntos S4</th><th>Zona FAAB al corte</th></tr></thead><tbody>${t.filas.map(x=>`<tr class="${x.equipo==='Team Orlando'?'mine-row':''}"><td>${x.posicion_semana}</td><td>${esc(x.equipo)}</td><td>${num(x.puntos_semana)} <b>(${x.jugadores_por_jugar}/${x.jugadores_total} por jugar)</b></td><td>${esc(x.zona_bono)}</td></tr>`).join('')}</tbody></table></div></article>`;const vp=t.codigo==='COPPER 142',h2h=t.filas.some(x=>x.victorias!=null),hasDiv=t.filas.some(x=>x.division),full=t.modo_tabla==='ACUMULADO_COMPLETO_TERCEROS';return `<article class="standings"><h3>${esc(t.codigo)}</h3><div class="table-scroll"><table><thead><tr><th>${full?'#':'# S3'}</th>${hasDiv?'<th>Div.</th>':''}<th>Equipo</th>${h2h?'<th>Réc.</th>':''}${vp?'<th>VP ganados<br>al corte</th><th>VP totales<br>al corte</th>':''}<th>${full?'Semana 4 al corte':'Semana 4 revisada'}</th><th>${full?'Acum. al corte':'Acum. parcial'}</th></tr></thead><tbody>${t.filas.map(x=>`<tr class="${x.equipo==='Team Orlando'?'mine-row':''}"><td>${x.posicion??'Pendiente'}</td>${hasDiv?`<td>${esc(x.division.replace('División ','D'))}</td>`:''}<td>${esc(x.equipo)}${x.nota?`<small>${esc(x.nota)}</small>`:''}</td>${h2h?`<td>${x.victorias}-${x.derrotas}</td>`:''}${vp?`<td>${x.vp_semana??'Pendiente'}</td><td>${x.vp??'Pendiente'}</td>`:''}<td>${x.auditado?`${num(x.puntos_semana)} <b>(${x.jugadores_por_jugar}/${x.jugadores_total} por jugar)</b>`:'<span class="muted">Pendiente</span>'}</td><td>${num(x.puntos)}${x.auditado?'':`<small>base Semana 3</small>`}</td></tr>`).join('')}</tbody></table></div></article>`}).join('');
const rules=['H2H divisional; líderes de división y criterios de puntos/récord definen playoffs.','H2H divisional; la tabla se separa por las dos divisiones.','Victory Points: 2 VP por H2H + 2/1/0 VP según top 4, puestos 5–8 o bottom 4 semanal.','Contender: H2H en Semanas 1–11; luego all-play, playoff interno y Quad 16.','Guillotine: Semanas 1–6 acumulan sin eliminación; top 4 semanal +$50 FAAB y puestos 5–8 +$25.'];
document.querySelectorAll('.standings h3').forEach((h,i)=>h.insertAdjacentHTML('afterend',`<p class="rule-note">${rules[i]}</p>`));

const gameCut=c=>c?`<div class="game-cut"><span>${esc(c.corte.replaceAll('_',' '))}</span><strong>${esc(c.visitante)} ${c.puntos_visitante}–${c.puntos_local} ${esc(c.local)}</strong><small>Corte exacto · resultados provisionales</small></div>`:'';
const playerCut=p=>p.corte?`<span class="player-cut"><b>${num(p.corte.puntos_ppr_provisionales)} pts reales</b> · proy. ${projected(p)}${p.corte.recepciones!=null?` · ${p.corte.recepciones} rec, ${p.corte.yardas_recepcion} yd${p.corte.recepcion_td?`, ${p.corte.recepcion_td} TD`:''}`:''}</span>`:'';
const timelinePlayer=p=>`<li><strong>${esc(p.nombre)}</strong><small>${esc(p.liga_codigo)} · ${esc(p.slot)} · ${playerIdentity(p.posicion,p.dorsal,p.equipo_nfl)} · ${projected(p)}</small>${playerCut(p)}</li>`;
const relatedGame=p=>`<div class="related-game"><span><b>${esc(p.momento)}</b>${esc(p.fecha_label)} · ${esc(p.evento)}</span><em class="related-${p.estado.toLowerCase()}">${esc(p.estado)}</em></div>`;
const currentGameStatus=b=>b.piernas.some(p=>/PERD/i.test(p.estado))?'PERDIDO':b.piernas.length&&b.piernas.every(p=>/ACERT|GANAD/i.test(p.estado))?'ACERTADO':'PENDIENTE';
const gameStatusBadge=b=>{const status=currentGameStatus(b);return `<span class="game-status game-status-${status.toLowerCase()}">${status==='ACERTADO'?'🟢':status==='PERDIDO'?'🔴':'🟡'} PARTIDO ${status}</span>`};
const legStatus=p=>`<strong class="timeline-leg-status timeline-leg-${/ACERT|GANAD/i.test(p.estado)?'win':/PERD/i.test(p.estado)?'lost':'pending'}">${legIcon(p.estado)} ${esc(p.estado)}</strong>`;
const couponProgress=b=>{const n=b.total_partidos,remaining=b.partidos_restantes;const remainingText=n===1?'Partido único del cupón':remaining===1?'Queda 1 por jugar: este partido':`Quedan ${remaining} por jugar, incluido este`;return `<div class="coupon-progress"><div><strong>Partido ${b.partido_numero} de ${n}</strong><span>${remainingText}</span></div>${b.partidos_relacionados.length?`<div class="related-games"><b>Todos los demás partidos de ${esc(b.codigo)}</b>${b.partidos_relacionados.map(relatedGame).join('')}</div>`:''}</div>`};
document.querySelector('#timeline').innerHTML=D.cronologia.length?D.cronologia.map((c,i)=>`<article class="timeline-card"><div class="game-row"><div><div class="timeline-order">${i+1} · ${esc(c.deporte)}</div><h3>${sportIcon(c.deporte)} ${esc(c.evento)}</h3><div class="game-meta">${esc(c.fecha_label)} · hora de Chile</div></div><div class="timeline-counts"><span>${c.apuestas.length} ${c.apuestas.length===1?'cupón':'cupones'}</span>${c.mostrar_fantasy?`<span>${c.fantasy_propios.length} tuyos</span><span>${c.fantasy_rivales.length} rivales</span>`:''}</div></div>${gameCut(c.corte)}<div class="timeline-columns${c.mostrar_fantasy?'':' bets-only'}"><section class="timeline-block bets"><h4>🎟️ APUESTAS</h4>${c.apuestas.length?c.apuestas.map(b=>`<div class="timeline-bet ${b.doctor?'doctor-timeline-bet':''}"><div class="timeline-bet-head"><strong>${esc(b.codigo)} <small>(${b.total_partidos} partido${b.total_partidos===1?'':'s'})</small>${b.doctor?` <span class="doctor-badge">🩺 ${esc(b.doctor.fuente_doctor)}${b.doctor.tipo_recomendacion==='ALTERNATIVA_ADAPTADA'?' · ALTERNATIVA ADAPTADA':''}</span>`:''}</strong>${gameStatusBadge(b)}</div>${couponProgress(b)}<div class="bet-money"><span>Apuesta ${b.apuesta_gratis_centavos?`${money(b.apuesta_gratis_centavos)} gratis`:money(b.apuesta_centavos)}</span><span>Cobro ${money(b.cobro_potencial_centavos)}</span><span>Neto ${money(b.ganancia_neta_potencial_centavos)}</span></div><ul>${b.piernas.map(p=>`<li>${esc(p.seleccion)}${legStatus(p)}<small>${propIdentity(p)?`${propIdentity(p)} · `:''}${esc(p.mercado)}</small>${cutLabel(p.corte)}</li>`).join('')}</ul></div>`).join(''):'<p class="timeline-empty">Sin apuestas en este partido</p>'}</section>${c.mostrar_fantasy?`<section class="timeline-block own"><h4>🟢 TÚ · FANTASY</h4>${c.fantasy_propios.length?`<ul class="timeline-players">${c.fantasy_propios.map(timelinePlayer).join('')}</ul>`:'<p class="timeline-empty">Sin titulares propios</p>'}</section><section class="timeline-block rival"><h4>🔴 RIVAL · FANTASY</h4>${c.fantasy_rivales.length?`<ul class="timeline-players">${c.fantasy_rivales.map(timelinePlayer).join('')}</ul>`:'<p class="timeline-empty">Sin titulares rivales</p>'}</section>`:''}</div></article>`).join(''):'<div class="notice"><strong>Sin eventos vinculados:</strong> no hay apuestas ni jugadores Fantasy pendientes en la agenda.</div>';

document.querySelector('#fantasy-live-cuts').innerHTML=D.fantasy_cortes.length?D.fantasy_cortes.map(c=>`<article class="fantasy-cut-card">${gameCut(c.corte)}<div class="timeline-columns"><section class="timeline-block own"><h4>🟢 TÚ · FANTASY</h4>${c.fantasy_propios.length?`<ul class="timeline-players">${c.fantasy_propios.map(timelinePlayer).join('')}</ul>`:'<p class="timeline-empty">Sin titulares propios</p>'}</section><section class="timeline-block rival"><h4>🔴 RIVAL · FANTASY</h4>${c.fantasy_rivales.length?`<ul class="timeline-players">${c.fantasy_rivales.map(timelinePlayer).join('')}</ul>`:'<p class="timeline-empty">Sin titulares rivales</p>'}</section></div></article>`).join(''):'<p class="notice">Todavía no hay cortes de partidos con titulares Fantasy.</p>';

document.querySelectorAll('.reveal').forEach(btn=>btn.addEventListener('click',()=>{const box=btn.closest('.spoiler');box.classList.toggle('locked');const timeline=!!btn.closest('#cronologia');const show=btn.dataset.show||(timeline?'👁 Mostrar cronología':'👁 Mostrar resultados');const hide=btn.dataset.hide||(timeline?'🙈 Ocultar cronología':'🙈 Ocultar resultados');btn.textContent=box.classList.contains('locked')?show:hide;}));
const links=[...document.querySelectorAll('.tabs a')],sections=[...document.querySelectorAll('main section')];
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`));}),{rootMargin:'-35% 0px -60% 0px'});sections.forEach(s=>observer.observe(s));

const lineupWeek=D.meta.semana_alineaciones||D.alineaciones_propuestas[0]?.semana||4;
const resultsWeek=D.meta.semana_resultados||D.posiciones[0]?.semana||4;
document.querySelector('#fantasy .eyebrow').textContent=decodeText(`NFL FANTASY · SEMANA ${lineupWeek}`);
document.querySelector('#fantasy .lineup-notice').textContent=decodeText(D.meta.nota_datos||'Plantillas y cortes conservados en el archivo; consulta la fecha de cada liga.');
document.querySelectorAll('#fantasy .fantasy-results-heading .eyebrow')[0].textContent=`WAIVERS · SEMANA ${lineupWeek}`;
document.querySelectorAll('#fantasy .fantasy-results-heading .eyebrow')[1].textContent=`RESULTADOS · SEMANA ${resultsWeek}`;
document.querySelectorAll('#fantasy .lineup-notice')[1].textContent='Pujas, propuestas y adjudicaciones conservan su estado individual. Ningún movimiento fue ejecutado por el asistente.';
document.querySelector('#tablas h2').textContent=decodeText(`Tablas · cierre Semana ${resultsWeek}`);
document.querySelector('#tablas .notice').textContent=decodeText('Solo partidos revisados. Las tablas muestran la semana cerrada; las plantillas corresponden a la semana indicada en Fantasy. VP no informados aparecen pendientes.');

};
